name: "azure resources deployment"

on:
  workflow_dispatch:

jobs:
  resources_deployment:
    name: "resources deployment"
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
