name: "azure resources deployment"

on:
  workflow_dispatch:

jobs:
  resources_deployment:
    name: "resources deployment"
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: resource group deployment
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az deployment sub create \
            -n 'rg-deployment' \
            -g 'prt-rg-01' \
            -l 'centralindia' \
            -f 'infra\resourceGroup.bicep' \
            -p applicationName='prt' \
            -p location='centralindia' \
            -p env='dev'

      - name: PRT Resources Deployment
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az deployment group create \
            -n 'prt-resource-deployment' \
            -f 'infra\main.bicep' \
            -p applicationName='prt' \
            -p location='centralindia' \
            -p administratorLogin='azureSqlUser' \
            -p administratorLoginPassword='Ant@Win1234' \
            -p env='dev'
