name: "git hub actions workflow"
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  job_id:
    name: "job 1"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - run: Github actions
